export const category = [
    { label: "Ambiental", value: "AM" },
    { label: "Salud", value: "SA" },
    { label: "Educación", value: "ED" },
    { label: "Igualdad Social", value: "IS" },
    { label: "Alimentación", value: "AL" },
    { label: "Vivienda", value: "VI" }             
  ];

export const resourceType = [
    { label: "Voluntarios", value: "VO" },
    { label: "Recurso económico", value: "RE" }      
  ];  

export const role = [
    { label: "Voluntario", value: "VO" },
    { label: "Líder de proyecto", value: "PM" },    
    { label: "Sponsor", value: "SP" }      
  ];  

export const cities = [
    { label: "ABEJORRAL - ANTIOQUIA", value: "05002" },
    { label: "ÁBREGO - NORTE DE SANTANDER", value: "54003" },
    { label: "ABRIAQUI - ANTIOQUIA", value: "05004" },
    { label: "ACACIAS - META", value: "50006" },
    { label: "ACANDI - CHOCO", value: "27006" },
    { label: "ACEVEDO - HUILA", value: "41006" },
    { label: "ACHI - BOLIVAR", value: "13006" },
    { label: "AGRADO - HUILA", value: "41013" },
    { label: "AGUA DE DIOS - CUNDINAMARCA", value: "25001" },
    { label: "AGUACHICA - CESAR", value: "20011" },
    { label: "AGUADA -SANTANDER - SANTANDER", value: "68013" },
    { label: "AGUADAS -CALDAS - CALDAS", value: "17013" },
    { label: "AGUAZUL - CASANARE", value: "85010" },
    { label: "AGUSTIN CODAZZI - CESAR", value: "20013" },
    { label: "AIPE - HUILA", value: "41016" },
    { label: "ALBÁN -CUNDINAMARCA - CUNDINAMARCA", value: "25019" },
    { label: "ALBAN -NARINO - NARIÑO", value: "52019" },
    { label: "ALBANIA -CAQUETA - CAQUETA", value: "18029" },
    { label: "ALBANIA -SANTANDER - SANTANDER", value: "68020" },
    { label: "ALBANIA-LA GUAJIRA - LA GUAJIRA", value: "44035" },
    { label: "ALCALA - VALLE DEL CAUCA", value: "76020" },
    { label: "ALDANA - NARIÑO", value: "52022" },
    { label: "ALEJANDRIA - ANTIOQUIA", value: "05021" },
    { label: "ALGARROBO-MAGDALENA - MAGDALENA", value: "47030" },
    { label: "ALGECIRAS - HUILA", value: "41020" },
    { label: "ALMAGUER - CAUCA", value: "19022" },
    { label: "ALMEIDA - BOYACA", value: "15022" },
    { label: "ALPUJARRA - TOLIMA", value: "73024" },
    { label: "ALTAMIRA - HUILA", value: "41026" },
    { label: "ALTO BAUDO - CHOCO", value: "27025" },
    { label: "ALTOS DEL ROSARIO-BOLIVAR - BOLIVAR", value: "13030" },
    { label: "ALVARADO - TOLIMA", value: "73026" },
    { label: "AMAGA - ANTIOQUIA", value: "05030" },
    { label: "AMALFI - ANTIOQUIA", value: "05031" },
    { label: "AMBALEMA - TOLIMA", value: "73030" },
    { label: "ANAPOIMA - CUNDINAMARCA", value: "25035" },
    { label: "ANCUYA - NARIÑO", value: "52036" },
    { label: "ANDALUCIA - VALLE DEL CAUCA", value: "76036" },
    { label: "ANDES - ANTIOQUIA", value: "05034" },
    { label: "ANGELOPOLIS - ANTIOQUIA", value: "05036" },
    { label: "ANGOSTURA - ANTIOQUIA", value: "05038" },
    { label: "ANOLAIMA - CUNDINAMARCA", value: "25040" },
    { label: "ANORI - ANTIOQUIA", value: "05040" },
    { label: "ANSERMA - CALDAS", value: "17042" },
    { label: "ANSERMANUEVO - VALLE DEL CAUCA", value: "76041" },
    { label: "ANZA - ANTIOQUIA", value: "05044" },
    { label: "ANZOATEGUI - TOLIMA", value: "73043" },
    { label: "APARTADO - ANTIOQUIA", value: "05045" },
    { label: "APÍA - RISARALDA", value: "66045" },
    { label: "APULO - CUNDINAMARCA", value: "25599" },
    { label: "AQUITANIA - BOYACA", value: "15047" },
    { label: "ARACATACA - MAGDALENA", value: "47053" },
    { label: "ARANZAZU - CALDAS", value: "17050" },
    { label: "ARATOCA - SANTANDER", value: "68051" },
    { label: "ARAUCA - ARAUCA", value: "81001" },
    { label: "ARAUQUITA - ARAUCA", value: "81065" },
    { label: "ARBELAEZ - CUNDINAMARCA", value: "25053" },
    { label: "ARBOLEDA -NARINO - NARIÑO", value: "52051" },
    { label: "ARBOLEDAS -NTE SDER - NORTE DE SANTANDER", value: "54051" },
    { label: "ARBOLETES - ANTIOQUIA", value: "05051" },
    { label: "ARCABUCO - BOYACA", value: "15051" },
    { label: "ARENAL-BOLIVAR - BOLIVAR", value: "13042" },
    { label: "ARGELIA - CAUCA - CAUCA", value: "19050" },
    { label: "ARGELIA - VALLE DEL CAUCA - VALLE DEL CAUCA", value: "76054" },
    { label: "ARGELIA /Antioquia - ANTIOQUIA", value: "05055" },
    { label: "ARIGUANI - MAGDALENA", value: "47058" },
    { label: "ARJONA - BOLIVAR - BOLIVAR", value: "13052" },
    { label: "ARMENIA - ANTIOQUIA", value: "05059" },
    { label: "ARMENIA - QUINDIO - QUINDIO", value: "63001" },
    { label: "ARMERO - TOLIMA", value: "73055" },
    { label: "ARROYOHONDO-BOLIVAR - BOLIVAR", value: "13062" },
    { label: "ASTREA - CESAR", value: "20032" },
    { label: "ATACO - TOLIMA", value: "73067" },
    { label: "ATRATO-CHOCO - CHOCO", value: "27050" },
    { label: "AYAPEL - CORDOBA", value: "23068" },
    { label: "BAGADO - CHOCO", value: "27073" },
    { label: "BAHÍA SOLANO - CHOCO", value: "27075" },
    { label: "BAJO BAUDO - CHOCO", value: "27077" },
    { label: "BAJO SANJUAN - CHOCO", value: "27082" },
    { label: "BALBOA - CAUCA - CAUCA", value: "19075" },
    { label: "BALBOA - RISARALDA - RISARALDA", value: "66075" },
    { label: "BARANOA - ATLANTICO", value: "08078" },
    { label: "BARAYA - HUILA", value: "41078" },
    { label: "BARBACOAS - NARIÑO", value: "52079" },
    { label: "BARBOSA - SANTANDER", value: "68077" },
    { label: "BARBOSA -ANTIOQUIA - ANTIOQUIA", value: "05079" },
    { label: "BARICHARA - SANTANDER", value: "68079" },
    { label: "BARRANCA DE UPIA - META", value: "50110" },
    { label: "BARRANCABERMEJA - SANTANDER", value: "68081" },
    { label: "BARRANCAS - LA GUAJIRA", value: "44078" },
    { label: "BARRANCO DE LOBA - BOLIVAR", value: "13074" },
    { label: "BARRANCO MINAS - GUAINIA - GUAINÍA", value: "94343" },
    { label: "BARRANQUILLA - ATLANTICO", value: "08001" },
    { label: "BECERRIL - CESAR", value: "20045" },
    { label: "BELALCÁZAR - CALDAS", value: "17088" },
    { label: "BELEN -BOYACA - BOYACA", value: "15087" },
    { label: "BELEN DE BAJIRA-CHOCO - CHOCO", value: "27086" },
    { label: "BELEN DE LOS ANDAQUÍES - CAQUETA", value: "18094" },
    { label: "BELEN DE UMBRÍA - RISARALDA", value: "66088" },
    { label: "BELEN -NARINO - NARIÑO", value: "52083" },
    { label: "BELLO - ANTIOQUIA", value: "05088" },
    { label: "BELMIRA - ANTIOQUIA", value: "05086" },
    { label: "BELTRAN - CUNDINAMARCA", value: "25086" },
    { label: "BERBEO - BOYACA", value: "15090" },
    { label: "BETANIA - ANTIOQUIA", value: "05091" },
    { label: "BETEITIVA - BOYACA", value: "15092" },
    { label: "BETULIA - ANTIOQUIA - ANTIOQUIA", value: "05093" },
    { label: "BETULIA - SANTANDER - SANTANDER", value: "68092" },
    { label: "BITUIMA - CUNDINAMARCA", value: "25095" },
    { label: "BOAVITA - BOYACA", value: "15097" },
    { label: "BOCHALEMA - NORTE DE SANTANDER", value: "54099" },
    { label: "BOGOTA - BOGOTA D.C", value: "11001" },
    { label: "BOJACA - CUNDINAMARCA", value: "25099" },
    { label: "BOJAYA - CHOCO", value: "27099" },
    { label: "BOLÍVAR - CAUCA - CAUCA", value: "19100" },
    { label: "BOLÍVAR - SANTANDER - SANTANDER", value: "68101" },
    { label: "BOLÍVAR - VALLE DEL CAUCA - VALLE DEL CAUCA", value: "76100" },
    { label: "BOLIVAR ANTIOQUIA - ANTIOQUIA", value: "05101" },
    { label: "BOSA - BOGOTA D.C", value: "11002" },
    { label: "BOSCONIA - CESAR", value: "20060" },
    { label: "BOYACÁ - BOYACA", value: "15104" },
    { label: "BRICEÑO - ANTIOQUIA", value: "05107" },
    { label: "BRICEÑO - BOYACA", value: "15106" },
    { label: "BUCARAMANGA - SANTANDER", value: "68001" },
    { label: "BUCARASICA - NORTE DE SANTANDER", value: "54109" },
    { label: "BUENAVENTURA - VALLE DEL CAUCA", value: "76109" },
    { label: "BUENAVISTA - BOYACA - BOYACA", value: "15109" },
    { label: "BUENAVISTA - CORDOBA - CORDOBA", value: "23079" },
    { label: "BUENAVISTA - QUINDIO - QUINDIO", value: "63111" },
    { label: "BUENAVISTA - SUCRE - SUCRE", value: "70110" },
    { label: "BUENOS AIRES - CAUCA", value: "19110" },
    { label: "BUESACO - NARIÑO", value: "52110" },
    { label: "BUGA - VALLE DEL CAUCA", value: "76111" },
    { label: "BUGALAGRANDE - VALLE DEL CAUCA", value: "76113" },
    { label: "BURITICA - ANTIOQUIA", value: "05113" },
    { label: "BUSBANZÁ - BOYACA", value: "15114" },
    { label: "CABRERA - CUNDINAMARCA - CUNDINAMARCA", value: "25120" },
    { label: "CABRERA - SANTANDER - SANTANDER", value: "68121" },
    { label: "CABUYARO - META", value: "50124" },
    { label: "CACAHUAL-GUAINIA - GUAINÍA", value: "94886" },
    { label: "CACERES - ANTIOQUIA", value: "05120" },
    { label: "CACHIPAY - CUNDINAMARCA", value: "25123" },
    { label: "CÁCHIRA - NORTE DE SANTANDER", value: "54128" },
    { label: "CÁCOTA - NORTE DE SANTANDER", value: "54125" },
    { label: "CAICEDO - ANTIOQUIA", value: "05125" },
    { label: "CAICEDONIA - VALLE DEL CAUCA", value: "76122" },
    { label: "CAIMITO - SUCRE", value: "70124" },
    { label: "CAJAMARCA - TOLIMA", value: "73124" },
    { label: "CAJIBÍO - CAUCA", value: "19130" },
    { label: "CAJICÁ - CUNDINAMARCA", value: "25126" },
    { label: "CALAMAR - BOLIVAR", value: "13140" },
    { label: "CALAMAR - GUAVIARE", value: "95015" },
    { label: "CALARCÁ - QUINDIO", value: "63130" },
    { label: "CALDAS - BOYACA - BOYACA", value: "15131" },
    { label: "CALDAS -ANTIOQUIA - ANTIOQUIA", value: "05129" },
    { label: "CALDONO - CAUCA", value: "19137" },
    { label: "CALI - VALLE DEL CAUCA", value: "76001" },
    { label: "CALIFORNIA - SANTANDER", value: "68132" },
    { label: "CALIMA - VALLE DEL CAUCA", value: "76126" },
    { label: "CALOTO - CAUCA", value: "19142" },
    { label: "CAMPAMENTO - ANTIOQUIA", value: "05134" },
    { label: "CAMPO DE LA CRUZ - ATLANTICO", value: "08137" },
    { label: "CAMPOALEGRE -HUILA - HUILA", value: "41132" },
    { label: "CAMPOHERMOSO -BOYACA - BOYACA", value: "15135" },
    { label: "CANALETE - CORDOBA", value: "23090" },
    { label: "CANDELARIA /Atlantico - ATLANTICO", value: "08141" },
    { label: "CANDELARIA /V.Cauca - VALLE DEL CAUCA", value: "76130" },
    { label: "CANTAGALLO-BOLIVAR - BOLIVAR", value: "13160" },
    { label: "CANTÓN DEL SAN PABLO - CHOCO", value: "27135" },
    { label: "CAÑASGORDAS - ANTIOQUIA", value: "05138" },
    { label: "CAPARRAPÍ - CUNDINAMARCA", value: "25148" },
    { label: "CAPITANEJO - SANTANDER", value: "68147" },
    { label: "CÁQUEZA - CUNDINAMARCA", value: "25151" },
    { label: "CARACOLI - ANTIOQUIA", value: "05142" },
    { label: "CARAMANTA - ANTIOQUIA", value: "05145" },
    { label: "CARCASÍ - SANTANDER", value: "68152" },
    { label: "CAREPA - ANTIOQUIA", value: "05147" },
    { label: "CARMEN APICALÁ - TOLIMA", value: "73148" },
    { label: "CARMEN DE CARUPA - CUNDINAMARCA", value: "25154" },
    { label: "CARMEN DE VIBORAL -ANTIOQ - ANTIOQUIA", value: "05148" },
    { label: "CARMEN DEL DARIEN - CHOCO", value: "27150" },
    { label: "CAROLINA - ANTIOQUIA", value: "05150" },
    { label: "CARTAGENA - BOLIVAR", value: "13001" },
    { label: "CARTAGENA DEL CHAIRÁ - CAQUETA", value: "18150" },
    { label: "CARTAGO - VALLE DEL CAUCA", value: "76147" },
    { label: "CARURU - VAUPÉS", value: "97161" },
    { label: "CASABIANCA - TOLIMA", value: "73152" },
    { label: "CASTILLA LA NUEVA - META", value: "50150" },
    { label: "CAUCASIA - ANTIOQUIA", value: "05154" },
    { label: "CEPITÁ - SANTANDER", value: "68160" },
    { label: "CERETÉ - CORDOBA", value: "23162" },
    { label: "CERINZA - BOYACA", value: "15162" },
    { label: "CERRITO - SANTANDER", value: "68162" },
    { label: "CERRO SAN ANTONIO - MAGDALENA", value: "47161" },
    { label: "CERTEGUI - CHOCO", value: "27160" },
    { label: "CHACHAGUÍ - NARIÑO", value: "52240" },
    { label: "CHAGUANÍ - CUNDINAMARCA", value: "25168" },
    { label: "CHALÁN - SUCRE", value: "70230" },
    { label: "CHÁMEZA - CASANARE", value: "85015" },
    { label: "CHAPARRAL - TOLIMA", value: "73168" },
    { label: "CHARALÁ - SANTANDER", value: "68167" },
    { label: "CHARTA - SANTANDER", value: "68169" },
    { label: "CHÍA - CUNDINAMARCA", value: "25175" },
    { label: "CHICORAL - TOLIMA", value: "73175" },
    { label: "CHIGORODO - ANTIOQUIA", value: "05172" },
    { label: "CHIMA - CORDOBA - CORDOBA", value: "23168" },
    { label: "CHIMA - SANTANDER - SANTANDER", value: "68176" },
    { label: "CHIMICHAGUA - CESAR", value: "20175" },
    { label: "CHINÁCOTA - NORTE DE SANTANDER", value: "54172" },
    { label: "CHINAVITA - BOYACA", value: "15172" },
    { label: "CHINCHINÁ - CALDAS", value: "17174" },
    { label: "CHINÚ - CORDOBA", value: "23182" },
    { label: "CHIPAQUE - CUNDINAMARCA", value: "25178" },
    { label: "CHIPATÁ - SANTANDER", value: "68179" },
    { label: "CHIQUINQUIRÁ - BOYACA", value: "15176" },
    { label: "CHIQUIZA - BOYACA", value: "15232" },
    { label: "CHIRIGUANÁ - CESAR", value: "20178" },
    { label: "CHISCAS - BOYACA", value: "15180" },
    { label: "CHITA - BOYACA", value: "15183" },
    { label: "CHITAGÁ - NORTE DE SANTANDER", value: "54174" },
    { label: "CHITARAQUE - BOYACA", value: "15185" },
    { label: "CHIVATÁ - BOYACA", value: "15187" },
    { label: "CHIVOLÓ - MAGDALENA", value: "47170" },
    { label: "CHIVOR - BOYACA", value: "15236" },
    { label: "CHOACHÍ - CUNDINAMARCA", value: "25181" },
    { label: "CHOCONTÁ - CUNDINAMARCA", value: "25183" },
    { label: "CICUCO - BOLIVAR", value: "13188" },
    { label: "CIÉNAGA DE ORO -CORDOBA - CORDOBA", value: "23189" },
    { label: "CIÉNAGA -MAGDALENA - MAGDALENA", value: "47189" },
    { label: "CIENEGA -BOYACA - BOYACA", value: "15189" },
    { label: "CIMITARRA - SANTANDER", value: "68190" },
    { label: "CIRCASIA - QUINDIO", value: "63190" },
    { label: "CISNEROS - ANTIOQUIA", value: "05190" },
    { label: "CIUDADANO EXTRANJERO - VICHADA", value: "99999" },
    { label: "CLEMENCIA-BOLIVAR - BOLIVAR", value: "13222" },
    { label: "COCORNA - ANTIOQUIA", value: "05197" },
    { label: "COELLO - TOLIMA", value: "73200" },
    { label: "COGUA - CUNDINAMARCA", value: "25200" },
    { label: "COLOMBIA - HUILA", value: "41206" },
    { label: "COLÓN - NARINO - NARIÑO", value: "52203" },
    { label: "COLÓN - PUTUMAYO - PUTUMAYO", value: "86219" },
    { label: "COLOSÓ - SUCRE", value: "70204" },
    { label: "COMBITA - BOYACA", value: "15204" },
    { label: "CONCEPCION - ANTIOQUIA - ANTIOQUIA", value: "05206" },
    { label: "CONCEPCION - SANTANDER - SANTANDER", value: "68207" },
    { label: "CONCORDIA - ANTIOQUIA", value: "05209" },
    { label: "CONCORDIA - MAGDALENA", value: "47205" },
    { label: "CONDOTO - CHOCO", value: "27205" },
    { label: "CONFINES - SANTANDER", value: "68209" },
    { label: "CONSACÁ - NARIÑO", value: "52207" },
    { label: "CONTADERO - NARIÑO", value: "52210" },
    { label: "CONTRATACIÓN - SANTANDER", value: "68211" },
    { label: "CONVENCIÓN - NORTE DE SANTANDER", value: "54206" },
    { label: "COPACABANA - ANTIOQUIA", value: "05212" },
    { label: "COPER - BOYACA", value: "15212" },
    { label: "CORDOBA - BOLIVAR - BOLIVAR", value: "13212" },
    { label: "CORDOBA - NARINO - NARIÑO", value: "52215" },
    { label: "CORDOBA - QUINDIO - QUINDIO", value: "63212" },
    { label: "CORINTO - CAUCA", value: "19212" },
    { label: "COROMORO - SANTANDER", value: "68217" },
    { label: "COROZAL - SUCRE", value: "70215" },
    { label: "CORRALES - BOYACA", value: "15215" },
    { label: "COTA - CUNDINAMARCA", value: "25214" },
    { label: "COTORRA - CORDOBA", value: "23300" },
    { label: "COVARACHÍA - BOYACA", value: "15218" },
    { label: "COVEÑAS - SUCRE", value: "70221" },
    { label: "COYAIMA - TOLIMA", value: "73217" },
    { label: "CRAVO NORTE - ARAUCA", value: "81220" },
    { label: "CUASPUD - NARIÑO", value: "52224" },
    { label: "CUBARÁ - BOYACA", value: "15223" },
    { label: "CUBARRAL - META", value: "50223" },
    { label: "CUCAITA - BOYACA", value: "15224" },
    { label: "CUCUNUBÁ - CUNDINAMARCA", value: "25224" },
    { label: "CÚCUTA - NORTE DE SANTANDER", value: "54001" },
    { label: "CUCUTILLA - NORTE DE SANTANDER", value: "54223" },
    { label: "CUITIIVA - BOYACA", value: "15226" },
    { label: "CUMARAL - META", value: "50226" },
    { label: "CUMARIBO - VICHADA", value: "99773" },
    { label: "CUMBAL - NARIÑO", value: "52227" },
    { label: "CUMBITARA - NARIÑO", value: "52233" },
    { label: "CUNDAY - TOLIMA", value: "73226" },
    { label: "CURITÍ - SANTANDER", value: "68229" },
    { label: "CURRILLO - CAQUETA", value: "18205" },
    { label: "CURUMANÍ - CESAR", value: "20228" },
    { label: "DABEIDA - ANTIOQUIA", value: "05234" },
    { label: "DAGUA - VALLE DEL CAUCA", value: "76233" },
    { label: "DESCONOCIDA - VICHADA", value: "99998" },
    { label: "DIBULLA - LA GUAJIRA", value: "44090" },
    { label: "DISTRACCION - LA GUAJIRA", value: "44098" },
    { label: "DOLORES - TOLIMA", value: "73236" },
    { label: "DON MATIAS - ANTIOQUIA", value: "05237" },
    { label: "DOS QUEBRADAS - RISARALDA", value: "66170" },
    { label: "DUITAMA - BOYACA", value: "15238" },
    { label: "DURANIA - NORTE DE SANTANDER", value: "54239" },
    { label: "EBEJICO - ANTIOQUIA", value: "05240" },
    { label: "EL ÁGUILA - VALLE DEL CAUCA", value: "76243" },
    { label: "EL BAGRE - ANTIOQUIA", value: "05250" },
    { label: "EL BANCO - MAGDALENA", value: "47245" },
    { label: "EL CAIRO - VALLE DEL CAUCA", value: "76246" },
    { label: "EL CALVARIO - META", value: "50245" },
    { label: "EL CARMEN DE ATRATO-CHOCO - CHOCO", value: "27245" },
    { label: "EL CARMEN DE -BOLIVAR - BOLIVAR", value: "13244" },
    { label: "EL CARMEN DE CHUCURY SDER - SANTANDER", value: "68235" },
    { label: "EL CARMEN -NTE SANTAND - NORTE DE SANTANDER", value: "54245" },
    { label: "EL CASTILLO - META", value: "50251" },
    { label: "EL CERRITO -VALLE - VALLE DEL CAUCA", value: "76248" },
    { label: "EL CHARCO - NARIÑO", value: "52250" },
    { label: "EL COCUY - BOYACA", value: "15244" },
    { label: "EL COLEGIO - CUNDINAMARCA", value: "25245" },
    { label: "EL COPEY - CESAR", value: "20238" },
    { label: "EL DONCELLO - CAQUETA", value: "18247" },
    { label: "EL DORADO - META", value: "50270" },
    { label: "EL DOVIO - VALLE DEL CAUCA", value: "76250" },
    { label: "EL ENCANTO - AMAZONAS", value: "91263" },
    { label: "EL ESPINO - BOYACA", value: "15248" },
    { label: "EL FLORIÁN - SANTANDER", value: "68271" },
    { label: "EL GUACAMAYO - SANTANDER", value: "68245" },
    { label: "EL GUAMO - BOLIVAR", value: "13248" },
    { label: "EL MOLINO - LA GUAJIRA", value: "44110" },
    { label: "EL PASO - CESAR", value: "20250" },
    { label: "EL PAUJIL - CAQUETA", value: "18256" },
    { label: "EL PEÑOL - NARIÑO", value: "52254" },
    { label: "EL PEÑON - BOLIVAR", value: "13268" },
    { label: "EL PEÑÓN - CUNDINAMARCA", value: "25258" },
    { label: "EL PEÑÓN - SANTANDER", value: "68250" },
    { label: "EL PIÑÓN - MAGDALENA", value: "47258" },
    { label: "EL PLAYÓN - SANTANDER", value: "68255" },
    { label: "EL RETÉN - MAGDALENA", value: "47268" },
    { label: "EL RETORNO - GUAVIARE", value: "95025" },
    { label: "EL ROBLE - SUCRE", value: "70233" },
    { label: "EL ROSAL-CUNDINAMARCA - CUNDINAMARCA", value: "25260" },
    { label: "EL ROSARIO - NARIÑO", value: "52256" },
    { label: "EL SANTUARIO - ANTIOQUIA", value: "05697" },
    { label: "EL TABLÓN - NARIÑO", value: "52258" },
    { label: "EL TAMBO - CAUCA - CAUCA", value: "19256" },
    { label: "EL TAMBO - NARINO - NARIÑO", value: "52260" },
    { label: "EL TARRA - NORTE DE SANTANDER", value: "54250" },
    { label: "EL ZULIA - NORTE DE SANTANDER", value: "54261" },
    { label: "ELÍAS - HUILA", value: "41244" },
    { label: "ENCINO - SANTANDER", value: "68264" },
    { label: "ENCISO - SANTANDER", value: "68266" },
    { label: "ENGATIVA - BOGOTA D.C", value: "11003" },
    { label: "ENTRERRIOS - ANTIOQUIA", value: "05264" },
    { label: "ENVIGADO - ANTIOQUIA", value: "05266" },
    { label: "ESPINAL - TOLIMA", value: "73268" },
    { label: "FACATATIVÁ - CUNDINAMARCA", value: "25269" },
    { label: "FALÁN - TOLIMA", value: "73270" },
    { label: "FILADELFIA - CALDAS", value: "17272" },
    { label: "FILANDIA - QUINDIO", value: "63272" },
    { label: "FIRAVITOBA - BOYACA", value: "15272" },
    { label: "FLANDES - TOLIMA", value: "73275" },
    { label: "FLORENCIA - CAQUETA", value: "18001" },
    { label: "FLORENCIA - CAUCA", value: "19290" },
    { label: "FLORESTA - BOYACA", value: "15276" },
    { label: "FLORIDA VLL -CAUCA - VALLE DEL CAUCA", value: "76275" },
    { label: "FLORIDABLANCA - SANTANDER", value: "68276" },
    { label: "FÓMEQUE - CUNDINAMARCA", value: "25279" },
    { label: "FONSECA - LA GUAJIRA", value: "44279" },
    { label: "FONTIBSN - BOGOTA D.C", value: "11279" },
    { label: "FORTUL - ARAUCA", value: "81300" },
    { label: "FOSCA - CUNDINAMARCA", value: "25281" },
    { label: "FRANCISCO PIZARRO - NARIÑO", value: "52520" },
    { label: "FREDONIA - ANTIOQUIA", value: "05282" },
    { label: "FRESNO - TOLIMA", value: "73283" },
    { label: "FRONTINO - ANTIOQUIA", value: "05284" },
    { label: "FUENTE DE ORO - META", value: "50287" },
    { label: "FUNDACIÓN - MAGDALENA", value: "47288" },
    { label: "FUNES - NARIÑO", value: "52287" },
    { label: "FUNZA - CUNDINAMARCA", value: "25286" },
    { label: "FÚQUENE - CUNDINAMARCA", value: "25288" },
    { label: "FUSAGASUGÁ - CUNDINAMARCA", value: "25290" },
    { label: "GACHALÁ - CUNDINAMARCA", value: "25293" },
    { label: "GACHANCIPÁ - CUNDINAMARCA", value: "25295" },
    { label: "GACHANTIVÁ - BOYACA", value: "15293" },
    { label: "GACHETÁ - CUNDINAMARCA", value: "25297" },
    { label: "GALÁN - SANTANDER", value: "68296" },
    { label: "GALAPA - ATLANTICO", value: "08296" },
    { label: "GALERAS - SUCRE", value: "70235" },
    { label: "GAMA - CUNDINAMARCA", value: "25299" },
    { label: "GAMARRA - CESAR", value: "20295" },
    { label: "GÁMBITA - SANTANDER", value: "68298" },
    { label: "GAMEZA - BOYACA", value: "15296" },
    { label: "GARAGOA - BOYACA", value: "15299" },
    { label: "GARZÓN - HUILA", value: "41298" },
    { label: "GÉNOVA - QUINDIO", value: "63302" },
    { label: "GIGANTE - HUILA", value: "41306" },
    { label: "GINEBRA - VALLE DEL CAUCA", value: "76306" },
    { label: "GIRALDO - ANTIOQUIA", value: "05306" },
    { label: "GIRARDOT - CUNDINAMARCA", value: "25307" },
    { label: "GIRARDOTA - ANTIOQUIA", value: "05308" },
    { label: "GIRÓN - SANTANDER", value: "68307" },
    { label: "GOMEZ PLATA - ANTIOQUIA", value: "05310" },
    { label: "GONZÁLEZ - CESAR", value: "20310" },
    { label: "GRAMALOTE - NORTE DE SANTANDER", value: "54313" },
    { label: "GRANADA - ANTIOQUIA", value: "05313" },
    { label: "GRANADA -CUNDINAMARCA - CUNDINAMARCA", value: "25312" },
    { label: "GRANADA -META - META", value: "50313" },
    { label: "GUACA - SANTANDER", value: "68318" },
    { label: "GUACAMAYAS - BOYACA", value: "15317" },
    { label: "GUACARÍ - VALLE DEL CAUCA", value: "76318" },
    { label: "GUACHETÁ - CUNDINAMARCA", value: "25317" },
    { label: "GUACHUCAL - NARIÑO", value: "52317" },
    { label: "GUADALUPE - ANTIOQUIA - ANTIOQUIA", value: "05315" },
    { label: "GUADALUPE - HUILA - HUILA", value: "41319" },
    { label: "GUADALUPE - SANTANDER - SANTANDER", value: "68320" },
    { label: "GUADUAS - CUNDINAMARCA", value: "25320" },
    { label: "GUAITARILLA - NARIÑO", value: "52320" },
    { label: "GUALANDAY - TOLIMA", value: "73310" },
    { label: "GUALMATÁN - NARIÑO", value: "52323" },
    { label: "GUAMAL - MAGDALENA - MAGDALENA", value: "47318" },
    { label: "GUAMAL - META - META", value: "50318" },
    { label: "GUAMO - TOLIMA", value: "73319" },
    { label: "GUAPI - CAUCA", value: "19318" },
    { label: "GUAPOTÁ - SANTANDER", value: "68322" },
    { label: "GUARANDA - SUCRE", value: "70265" },
    { label: "GUARNE - ANTIOQUIA", value: "05318" },
    { label: "GUASCA - CUNDINAMARCA", value: "25322" },
    { label: "GUATAPE - ANTIOQUIA", value: "05321" },
    { label: "GUATAQUÍ - CUNDINAMARCA", value: "25324" },
    { label: "GUATAVITA - CUNDINAMARCA", value: "25326" },
    { label: "GUATEQUE - BOYACA", value: "15322" },
    { label: "GUÁTICA - RISARALDA", value: "66318" },
    { label: "GUAVATÁ - SANTANDER", value: "68324" },
    { label: "GUAYABAL DE SÍQUIMA - CUNDINAMARCA", value: "25328" },
    { label: "GUAYABETAL - CUNDINAMARCA", value: "25335" },
    { label: "GUAYATÁ - BOYACA", value: "15325" },
    { label: "GUEPSA - SANTANDER", value: "68327" },
    { label: "GÜICÁN - BOYACA", value: "15332" },
    { label: "GUTIÉRREZ - CUNDINAMARCA", value: "25339" },
    { label: "HACARÍ - NORTE DE SANTANDER", value: "54344" },
    { label: "HATILLO DE LOBA - BOLIVAR", value: "13300" },
    { label: "HATO - SANTANDER", value: "68344" },
    { label: "HATO COROZAL - CASANARE", value: "85125" },
    { label: "HATONUEVO - LA GUAJIRA", value: "44378" },
    { label: "HELICONIA - ANTIOQUIA", value: "05347" },
    { label: "HERRÁN - NORTE DE SANTANDER", value: "54347" },
    { label: "HERVEO - TOLIMA", value: "73347" },
    { label: "HISPANIA - ANTIOQUIA", value: "05353" },
    { label: "HOBO - HUILA", value: "41349" },
    { label: "HONDA - TOLIMA", value: "73349" },
    { label: "IBAGUE - TOLIMA", value: "73001" },
    { label: "ICONONZO - TOLIMA", value: "73352" },
    { label: "ILES - NARIÑO", value: "52352" },
    { label: "IMUÉS - NARIÑO", value: "52354" },
    { label: "INÍRIDA - GUAINÍA", value: "94001" },
    { label: "INZÁ - CAUCA", value: "19355" },
    { label: "IPIALES - NARIÑO", value: "52356" },
    { label: "IQUIRA - HUILA", value: "41357" },
    { label: "ISNOS - HUILA", value: "41359" },
    { label: "ISTMINA - CHOCO", value: "27361" },
    { label: "ITAGÜI - ANTIOQUIA", value: "05360" },
    { label: "ITUANGO - ANTIOQUIA", value: "05361" },
    { label: "IZA - BOYACA", value: "15362" },
    { label: "JAMBALÓ - CAUCA", value: "19364" },
    { label: "JAMUNDÍ - VALLE DEL CAUCA", value: "76364" },
    { label: "JARDIN - ANTIOQUIA", value: "05364" },
    { label: "JENESANO - BOYACA", value: "15367" },
    { label: "JERICO - ANTIOQUIA - ANTIOQUIA", value: "05368" },
    { label: "JERICO - BOYACA - BOYACA", value: "15368" },
    { label: "JERUSALÉN - CUNDINAMARCA", value: "25368" },
    { label: "JESÚS MARÍA - SANTANDER", value: "68368" },
    { label: "JORDÁN - SANTANDER", value: "68370" },
    { label: "JUAN DE ACOSTA - ATLANTICO", value: "08372" },
    { label: "JUNÍN - CUNDINAMARCA", value: "25372" },
    { label: "JURADÓ - CHOCO", value: "27372" },
    { label: "LA APARTADA - CORDOBA", value: "23350" },
    { label: "LA ARGENTINA - HUILA", value: "41378" },
    { label: "LA BELLEZA - SANTANDER", value: "68377" },
    { label: "LA CALERA - CUNDINAMARCA", value: "25377" },
    { label: "LA CAPILLA - BOYACA", value: "15380" },
    { label: "LA CEJA - ANTIOQUIA", value: "05376" },
    { label: "LA CELIA - RISARALDA", value: "66383" },
    { label: "LA CHORRERA - AMAZONAS", value: "91405" },
    { label: "LA CRUZ - NARIÑO", value: "52378" },
    { label: "LA CUMBRE - VALLE DEL CAUCA", value: "76377" },
    { label: "LA DORADA - CALDAS", value: "17380" },
    { label: "LA ESPERANZA - NORTE DE SANTANDER", value: "54385" },
    { label: "LA ESTRELLA - ANTIOQUIA", value: "05380" },
    { label: "LA FLORIDA - NARIÑO", value: "52381" },
    { label: "LA GLORIA - CESAR", value: "20383" },
    { label: "LA GUADALUPE - GUAINÍA", value: "94885" },
    { label: "LA JAGUA DE IBIRICO - CESAR", value: "20400" },
    { label: "LA JAGUA DEL PILAR - LA GUAJIRA", value: "44420" },
    { label: "LA LLANADA - NARIÑO", value: "52385" },
    { label: "LA MACARENA - META", value: "50350" },
    { label: "LA MERCED - CALDAS", value: "17388" },
    { label: "LA MESA - CUNDINAMARCA", value: "25386" },
    { label: "LA MONTAÑA - CAQUETA", value: "18410" },
    { label: "LA PALMA - CUNDINAMARCA", value: "25394" },
    { label: "LA PAZ - CESAR - CESAR", value: "20621" },
    { label: "LA PAZ - SANTANDER - SANTANDER", value: "68397" },
    { label: "LA PEDRERA - AMAZONAS", value: "91407" },
    { label: "LA PEÑA - CUNDINAMARCA", value: "25398" },
    { label: "LA PINTADA - ANTIOQUIA", value: "05390" },
    { label: "LA PLATA - HUILA", value: "41396" },
    { label: "LA PLAYA - NORTE DE SANTANDER", value: "54398" },
    { label: "LA PRIMAVERA - VICHADA", value: "99524" },
    { label: "LA SALINA - CASANARE", value: "85136" },
    { label: "LA SIERRA - CAUCA", value: "19392" },
    { label: "LA TEBAIDA - QUINDIO", value: "63401" },
    { label: "LA TOLA - NARIÑO", value: "52390" },
    { label: "LA UNION -ANTIOQUIA - ANTIOQUIA", value: "05400" },
    { label: "LA UNION -NARINO - NARIÑO", value: "52399" },
    { label: "LA UNION -SUCRE - SUCRE", value: "70400" },
    { label: "LA UNION -VALLE - VALLE DEL CAUCA", value: "76400" },
    { label: "LA UVITA - BOYACA", value: "15403" },
    { label: "LA VEGA - CAUCA - CAUCA", value: "19397" },
    { label: "LA VEGA - CUNDINAMARCA - CUNDINAMARCA", value: "25402" },
    { label: "LA VICTORIA -BOYACA - BOYACA", value: "15401" },
    { label: "LA VICTORIA -VALLE - VALLE DEL CAUCA", value: "76403" },
    { label: "LA VICTORIA-AMAZONAS - AMAZONAS", value: "91430" },
    { label: "LA VIRGINIA - RISARALDA", value: "66400" },
    { label: "LABATECA - NORTE DE SANTANDER", value: "54377" },
    { label: "LABRANZAGRANDE - BOYACA", value: "15377" },
    { label: "LANDÁZURI - SANTANDER", value: "68385" },
    { label: "LEBRIJA - SANTANDER", value: "68406" },
    { label: "LEIVA - NARIÑO", value: "52405" },
    { label: "LEJANÍAS - META", value: "50400" },
    { label: "LENGUAZAQUE - CUNDINAMARCA", value: "25407" },
    { label: "LÉRIDA - TOLIMA", value: "73408" },
    { label: "LETICIA - AMAZONAS", value: "91001" },
    { label: "LÍBANO - TOLIMA", value: "73411" },
    { label: "LIBORINA - ANTIOQUIA", value: "05411" },
    { label: "LINARES - NARIÑO", value: "52411" },
    { label: "LITORAL DEL BAJO SAN JUAN - CHOCO", value: "27250" },
    { label: "LLORÓ - CHOCO", value: "27413" },
    { label: "LÓPEZ - CAUCA", value: "19418" },
    { label: "LORICA - CORDOBA", value: "23417" },
    { label: "LOS ANDES - NARIÑO", value: "52418" },
    { label: "LOS CÓRDOBAS - CORDOBA", value: "23419" },
    { label: "LOS PALMITOS - SUCRE", value: "70418" },
    { label: "LOS PATIOS - NORTE DE SANTANDER", value: "54405" },
    { label: "LOS SANTOS - SANTANDER", value: "68418" },
    { label: "LOURDES - NORTE DE SANTANDER", value: "54418" },
    { label: "LURUACO - ATLANTICO", value: "08421" },
    { label: "MACANAL - BOYACA", value: "15425" },
    { label: "MACARAVITA - SANTANDER", value: "68425" },
    { label: "MACEO - ANTIOQUIA", value: "05425" },
    { label: "MACHETÁ - CUNDINAMARCA", value: "25426" },
    { label: "MADRID - CUNDINAMARCA", value: "25430" },
    { label: "MAGANGUÉ - BOLIVAR", value: "13430" },
    { label: "MAGUÍ - NARIÑO", value: "52427" },
    { label: "MAHATES - BOLIVAR", value: "13433" },
    { label: "MAICAO - LA GUAJIRA", value: "44430" },
    { label: "MAJAGUAL - SUCRE", value: "70429" },
    { label: "MÁLAGA - SANTANDER", value: "68432" },
    { label: "MALAMBO - ATLANTICO", value: "08433" },
    { label: "MALLAMA - NARIÑO", value: "52435" },
    { label: "MANATÍ - ATLANTICO", value: "08436" },
    { label: "MANAURE - CESAR", value: "20443" },
    { label: "MANAURE - LA GUAJIRA", value: "44560" },
    { label: "MANÍ - CASANARE", value: "85139" },
    { label: "MANIZALES - CALDAS", value: "17001" },
    { label: "MANTA - CUNDINAMARCA", value: "25436" },
    { label: "MANZANARES - CALDAS", value: "17433" },
    { label: "MAPIRIPÁN - META", value: "50325" },
    { label: "MAPIRIPANA - GUAINÍA", value: "94663" },
    { label: "MARGARITA - BOLIVAR", value: "13440" },
    { label: "MARIA LA BAJA - BOLIVAR", value: "13442" },
    { label: "MARINILLA - ANTIOQUIA", value: "05440" },
    { label: "MARIPÍ - BOYACA", value: "15442" },
    { label: "MARIQUITA - TOLIMA", value: "73443" },
    { label: "MARMATO - CALDAS", value: "17442" },
    { label: "MARQUETALIA - CALDAS", value: "17444" },
    { label: "MARSELLA - RISARALDA", value: "66440" },
    { label: "MARULANDA - CALDAS", value: "17446" },
    { label: "MATANZA - SANTANDER", value: "68444" },
    { label: "MEDELLIN - ANTIOQUIA", value: "05001" },
    { label: "MEDINA - CUNDINAMARCA", value: "25438" },
    { label: "MEDIO ATRATO - CHOCO", value: "27425" },
    { label: "MEDIO BAUDO - CHOCO", value: "27430" },
    { label: "MEDIO SAN JUAN - CHOCO", value: "27450" },
    { label: "MELGAR - TOLIMA", value: "73449" },
    { label: "MERCADERES - CAUCA", value: "19450" },
    { label: "MESETAS - META", value: "50330" },
    { label: "MILÁN - CAQUETA", value: "18460" },
    { label: "MIRAFLORES /Boyaca - BOYACA", value: "15455" },
    { label: "MIRAFLORES /Guaviare - GUAVIARE", value: "95200" },
    { label: "MIRANDA - CAUCA", value: "19455" },
    { label: "MIRITÍ-PARANÁ - AMAZONAS", value: "91460" },
    { label: "MISTRATÓ - RISARALDA", value: "66456" },
    { label: "MITÚ - VAUPÉS", value: "97001" },
    { label: "MOCOA - PUTUMAYO", value: "86001" },
    { label: "MOGOTES - SANTANDER", value: "68464" },
    { label: "MOLAGAVITA - SANTANDER", value: "68468" },
    { label: "MOMIL - CORDOBA", value: "23464" },
    { label: "MOMPÓS - BOLIVAR", value: "13468" },
    { label: "MONGUA - BOYACA", value: "15464" },
    { label: "MONGUÍ - BOYACA", value: "15466" },
    { label: "MONIQUIRÁ - BOYACA", value: "15469" },
    { label: "MONTEBELLO - ANTIOQUIA", value: "05467" },
    { label: "MONTECRISTO - BOLIVAR", value: "13458" },
    { label: "MONTELÍBANO - CORDOBA", value: "23466" },
    { label: "MONTENEGRO - QUINDIO", value: "63470" },
    { label: "MONTERIA - CORDOBA", value: "23001" },
    { label: "MONTERREY - CASANARE", value: "85162" },
    { label: "MOÑITOS - CORDOBA", value: "23500" },
    { label: "MORALES -BOLIVAR - BOLIVAR", value: "13473" },
    { label: "MORALES -CAUCA - CAUCA", value: "19473" },
    { label: "MORELIA - CAQUETA", value: "18479" },
    { label: "MORICHAL - GUAVIARE", value: "95220" },
    { label: "MORICHAL NUEVO - GUAINÍA", value: "94888" },
    { label: "MORROA - SUCRE", value: "70473" },
    { label: "MOSQUERA -CUNDINAMARCA - CUNDINAMARCA", value: "25473" },
    { label: "MOSQUERA -NARINO - NARIÑO", value: "52473" },
    { label: "MOTAVITA - BOYACA", value: "15476" },
    { label: "MURILLO - TOLIMA", value: "73461" },
    { label: "MURINDO - ANTIOQUIA", value: "05475" },
    { label: "MUTATA - ANTIOQUIA", value: "05480" },
    { label: "MUTISCUA - NORTE DE SANTANDER", value: "54480" },
    { label: "MUZO - BOYACA", value: "15480" },
    { label: "NARIÑO -ANTIOQUIA - ANTIOQUIA", value: "05483" },
    { label: "NARIÑO -CUNDINAMARCA - CUNDINAMARCA", value: "25483" },
    { label: "NARIÑO -NARINO - NARIÑO", value: "52480" },
    { label: "NÁTAGA - HUILA", value: "41483" },
    { label: "NATAGAIMA - TOLIMA", value: "73483" },
    { label: "NECHI - ANTIOQUIA", value: "05495" },
    { label: "NECOCLI - ANTIOQUIA", value: "05490" },
    { label: "NEIRA - CALDAS", value: "17486" },
    { label: "NEIVA - HUILA", value: "41001" },
    { label: "NEMOCÓN - CUNDINAMARCA", value: "25486" },
    { label: "NILO - CUNDINAMARCA", value: "25488" },
    { label: "NIMAIMA - CUNDINAMARCA", value: "25489" },
    { label: "NOBSA - BOYACA", value: "15491" },
    { label: "NOCAIMA - CUNDINAMARCA", value: "25491" },
    { label: "NORCASIA - CALDAS", value: "17495" },
    { label: "NOVITÁ - CHOCO", value: "27491" },
    { label: "NUEVA ANTIOQUIA - VICHADA", value: "99496" },
    { label: "NUEVA GRANADA - MAGDALENA", value: "47460" },
    { label: "NUEVO COLÓN - BOYACA", value: "15494" },
    { label: "NUNCHÍA - CASANARE", value: "85225" },
    { label: "NUQUÍ - CHOCO", value: "27495" },
    { label: "OBANDO - VALLE DEL CAUCA", value: "76497" },
    { label: "OCAMONTE - SANTANDER", value: "68498" },
    { label: "OCAÑA - NORTE DE SANTANDER", value: "54498" },
    { label: "OIBA - SANTANDER", value: "68500" },
    { label: "OICATA - BOYACA", value: "15500" },
    { label: "OLAYA - ANTIOQUIA", value: "05501" },
    { label: "OLAYA HERRERA - NARIÑO", value: "52490" },
    { label: "ONZAGA - SANTANDER", value: "68502" },
    { label: "OPORAPA - HUILA", value: "41503" },
    { label: "ORITO - PUTUMAYO", value: "86320" },
    { label: "OROCUÉ - CASANARE", value: "85230" },
    { label: "ORTEGA - TOLIMA", value: "73504" },
    { label: "OSPINA - NARIÑO", value: "52506" },
    { label: "OTANCHE - BOYACA", value: "15507" },
    { label: "OVEJAS - SUCRE", value: "70508" },
    { label: "PACHAVITA - BOYACA", value: "15511" },
    { label: "PACHO - CUNDINAMARCA", value: "25513" },
    { label: "PACOA - VAUPÉS", value: "97511" },
    { label: "PÁCORA - CALDAS", value: "17513" },
    { label: "PADILLA - CAUCA", value: "19513" },
    { label: "PÁEZ -BOYACA - BOYACA", value: "15514" },
    { label: "PÁEZ -CAUCA - CAUCA", value: "19517" },
    { label: "PAICOL - HUILA", value: "41518" },
    { label: "PAILITAS - CESAR", value: "20517" },
    { label: "PAIME - CUNDINAMARCA", value: "25518" },
    { label: "PAIPA - BOYACA", value: "15516" },
    { label: "PAJARITO - BOYACA", value: "15518" },
    { label: "PALERMO - HUILA", value: "41524" },
    { label: "PALESTINA -CALDAS - CALDAS", value: "17524" },
    { label: "PALESTINA -HUILA - HUILA", value: "41530" },
    { label: "PALMAR - SANTANDER", value: "68522" },
    { label: "PALMAR DE VALERA - ATLANTICO", value: "08520" },
    { label: "PALMAS DEL SOCORRO - SANTANDER", value: "68524" },
    { label: "PALMIRA - VALLE DEL CAUCA", value: "76520" },
    { label: "PALMITO - SUCRE", value: "70523" },
    { label: "PALO CABILDO - TOLIMA", value: "73520" },
    { label: "PAMPLONA - NORTE DE SANTANDER", value: "54518" },
    { label: "PAMPLONITA - NORTE DE SANTANDER", value: "54520" },
    { label: "PANA PANA - GUAINÍA", value: "94887" },
    { label: "PANDI - CUNDINAMARCA", value: "25524" },
    { label: "PANQUEBA - BOYACA", value: "15522" },
    { label: "PAPUNAHUA - VAUPÉS", value: "97777" },
    { label: "PÁRAMO - SANTANDER", value: "68533" },
    { label: "PARATEBUENO - CUNDINAMARCA", value: "25530" },
    { label: "PASCA - CUNDINAMARCA", value: "25535" },
    { label: "PASTO - NARIÑO", value: "52001" },
    { label: "PATÍA EL BORDO - CAUCA", value: "19532" },
    { label: "PAUNA - BOYACA", value: "15531" },
    { label: "PAYA - BOYACA", value: "15533" },
    { label: "PAZ DE ARIPORO - CASANARE", value: "85250" },
    { label: "PAZ DE RÍO - BOYACA", value: "15537" },
    { label: "PEDRAZA - MAGDALENA", value: "47541" },
    { label: "PELAYA - CESAR", value: "20550" },
    { label: "PENSILVANIA - CALDAS", value: "17541" },
    { label: "PEÑOL - ANTIOQUIA", value: "05541" },
    { label: "PEQUE - ANTIOQUIA", value: "05543" },
    { label: "PEREIRA - RISARALDA", value: "66001" },
    { label: "PESCA - BOYACA", value: "15542" },
    { label: "PIAMONTE - CAUCA", value: "19533" },
    { label: "PIEDECUESTA - SANTANDER", value: "68547" },
    { label: "PIEDRAS - TOLIMA", value: "73547" },
    { label: "PIENDAMÓ - CAUCA", value: "19548" },
    { label: "PIJAO - QUINDIO", value: "63548" },
    { label: "PIJINO DEL CARMEN - MAGDALENA", value: "47545" },
    { label: "PINCHOTE - SANTANDER", value: "68549" },
    { label: "PINILLOS - BOLIVAR", value: "13549" },
    { label: "PIOJÓ - ATLANTICO", value: "08549" },
    { label: "PISBA - BOYACA", value: "15550" },
    { label: "PITAL - HUILA", value: "41548" },
    { label: "PIVIJAY - MAGDALENA", value: "47551" },
    { label: "PLANADAS - TOLIMA", value: "73555" },
    { label: "PLANETA RICA - CORDOBA", value: "23555" },
    { label: "PLATO - MAGDALENA", value: "47555" },
    { label: "POLICARPA - NARIÑO", value: "52540" },
    { label: "POLONUEVO - ATLANTICO", value: "08558" },
    { label: "PONEDERA - ATLANTICO", value: "08560" },
    { label: "POPAYÁN - CAUCA", value: "19001" },
    { label: "PORE - CASANARE", value: "85263" },
    { label: "POTOSÍ - NARIÑO", value: "52560" },
    { label: "PRADERA - VALLE DEL CAUCA", value: "76563" },
    { label: "PRADO - TOLIMA", value: "73563" },
    { label: "PROVIDENCIA - NARIÑO", value: "52565" },
    { label: "PROVIDENCIA - SAN ANDRES, PROVIDENCIA Y STA CATALINA", value: "88564" },
    { label: "PTALITO - HUILA", value: "41551" },
    { label: "PTO SANTANDER-N.SANTANDER - NORTE DE SANTANDER", value: "54553" },
    { label: "PUEBLO BELLO - CESAR", value: "20570" },
    { label: "PUEBLO NUEVO - CORDOBA", value: "23570" },
    { label: "PUEBLO RICO -RISARALDA - RISARALDA", value: "66572" },
    { label: "PUEBLORRICO -ANTIOQUIA - ANTIOQUIA", value: "05576" },
    { label: "PUEBLOVIEJO - MAGDALENA", value: "47570" },
    { label: "PUENTE NACIONAL - SANTANDER", value: "68572" },
    { label: "PUERRES - NARIÑO", value: "52573" },
    { label: "PUERTO ALEGRÍA - AMAZONAS", value: "91530" },
    { label: "PUERTO ARICA - AMAZONAS", value: "91536" },
    { label: "PUERTO ASÍS - PUTUMAYO", value: "86568" },
    { label: "PUERTO BERRIO - ANTIOQUIA", value: "05579" },
    { label: "PUERTO BOYACÁ - BOYACA", value: "15572" },
    { label: "PUERTO CAICEDO - PUTUMAYO", value: "86569" },
    { label: "PUERTO CARREÑO - VICHADA", value: "99001" },
    { label: "PUERTO COLOMBIA -ATLANT - ATLANTICO", value: "08573" },
    { label: "PUERTO COLOMBIA-GUAINIA - GUAINÍA", value: "94884" },
    { label: "PUERTO CONCORDIA - META", value: "50450" },
    { label: "PUERTO ESCONDIDO - CORDOBA", value: "23574" },
    { label: "PUERTO GAITÁN - META", value: "50568" },
    { label: "PUERTO GUZMAN - PUTUMAYO", value: "86571" },
    { label: "PUERTO LEGUIZAMO - PUTUMAYO", value: "86573" },
    { label: "PUERTO LIBERTADOR - CORDOBA", value: "23580" },
    { label: "PUERTO LLERAS - META", value: "50577" },
    { label: "PUERTO LÓPEZ - META", value: "50573" },
    { label: "PUERTO NARE - ANTIOQUIA", value: "05585" },
    { label: "PUERTO NARIÑO - AMAZONAS", value: "91540" },
    { label: "PUERTO PARRA - SANTANDER", value: "68573" },
    { label: "PUERTO RICO -CAQUETA - CAQUETA", value: "18592" },
    { label: "PUERTO RICO -META - META", value: "50590" },
    { label: "PUERTO RONDON - ARAUCA", value: "81591" },
    { label: "PUERTO SALGAR - CUNDINAMARCA", value: "25572" },
    { label: "PUERTO SANTANDER-AMAZONAS - AMAZONAS", value: "91669" },
    { label: "PUERTO TEJADO - CAUCA", value: "19573" },
    { label: "PUERTO WILCHES - SANTANDER", value: "68575" },
    { label: "PUERTOTRIUNFO - ANTIOQUIA", value: "05591" },
    { label: "PULÍ - CUNDINAMARCA", value: "25580" },
    { label: "PUPIALES - NARIÑO", value: "52585" },
    { label: "PURACÉ - CAUCA", value: "19585" },
    { label: "PURIFICACIÓN - TOLIMA", value: "73585" },
    { label: "PURÍSIMA - CORDOBA", value: "23586" },
    { label: "QUEBRADANEGRA - CUNDINAMARCA", value: "25592" },
    { label: "QUETAME - CUNDINAMARCA", value: "25594" },
    { label: "QUIBDÓ - CHOCO", value: "27001" },
    { label: "QUIMBAYA - QUINDIO", value: "63594" },
    { label: "QUINCHÍA - RISARALDA", value: "66594" },
    { label: "QUIPAMA - BOYACA", value: "15580" },
    { label: "QUÍPILE - CUNDINAMARCA", value: "25596" },
    { label: "RAGONVALIA - NORTE DE SANTANDER", value: "54599" },
    { label: "RAMIRIQUÍ - BOYACA", value: "15599" },
    { label: "RAQUIRA - BOYACA", value: "15600" },
    { label: "RECETOR - CASANARE", value: "85279" },
    { label: "REGIDOR - BOLIVAR", value: "13580" },
    { label: "REMEDIOS - ANTIOQUIA", value: "05604" },
    { label: "REMOLINO - MAGDALENA", value: "47605" },
    { label: "REPELÓN - ATLANTICO", value: "08606" },
    { label: "RESTREPO -META - META", value: "50606" },
    { label: "RESTREPO-VALLE DEL CAUCA - VALLE DEL CAUCA", value: "76606" },
    { label: "RETIRO - ANTIOQUIA", value: "05607" },
    { label: "RICAURTE -CUNDINAMARCA - CUNDINAMARCA", value: "25612" },
    { label: "RICAURTE -NARINO - NARIÑO", value: "52612" },
    { label: "RÍO DE ORO - CESAR", value: "20614" },
    { label: "RÍO IRO - CHOCO", value: "27580" },
    { label: "RIO QUITO - CHOCO", value: "27600" },
    { label: "RIO VIEJO - BOLIVAR", value: "13600" },
    { label: "RIOBLANCO - TOLIMA", value: "73616" },
    { label: "RIOFRÍO - VALLE DEL CAUCA", value: "76616" },
    { label: "RIOHACHA - LA GUAJIRA", value: "44001" },
    { label: "RIONEGRO - ANTIOQUIA", value: "05615" },
    { label: "RIONEGRO - SANTANDER", value: "68615" },
    { label: "RIOSUCIO -CALDAS - CALDAS", value: "17614" },
    { label: "RIOSUCIO -CHOCO - CHOCO", value: "27615" },
    { label: "RISARALDA - CALDAS", value: "17616" },
    { label: "RIVERA - HUILA", value: "41615" },
    { label: "ROBERTO PAYÁN - NARIÑO", value: "52621" },
    { label: "ROLDANILLO - VALLE DEL CAUCA", value: "76622" },
    { label: "RONCESVALLES - TOLIMA", value: "73622" },
    { label: "RONDÓN - BOYACA", value: "15621" },
    { label: "ROSAS - CAUCA", value: "19622" },
    { label: "ROVIRA - TOLIMA", value: "73624" },
    { label: "S. JOSE DE OCUNE - VICHADA", value: "99760" },
    { label: "SABANA DE TORRES - SANTANDER", value: "68655" },
    { label: "SABANAGRANDE - ATLANTICO", value: "08634" },
    { label: "SABANALARGA -ANTIOQUIA - ANTIOQUIA", value: "05628" },
    { label: "SABANALARGA -ATLANTICO - ATLANTICO", value: "08638" },
    { label: "SABANALARGA -CASANARE - CASANARE", value: "85300" },
    { label: "SABANAS DE SAN ÁNGEL - MAGDALENA", value: "47660" },
    { label: "SABANETA - ANTIOQUIA", value: "05631" },
    { label: "SABOYÁ - BOYACA", value: "15632" },
    { label: "SÁCAMA - CASANARE", value: "85315" },
    { label: "SACHICA - BOYACA", value: "15638" },
    { label: "SAHAGÚN - CORDOBA", value: "23660" },
    { label: "SALADOBLANCO - HUILA", value: "41660" },
    { label: "SALAMINA -CALDAS - CALDAS", value: "17653" },
    { label: "SALAMINA -MAGDALENA - MAGDALENA", value: "47675" },
    { label: "SALAZAR - NORTE DE SANTANDER", value: "54660" },
    { label: "SALDAÑA - TOLIMA", value: "73671" },
    { label: "SALENTO - QUINDIO", value: "63690" },
    { label: "SALGAR - ANTIOQUIA", value: "05642" },
    { label: "SAMACÁ - BOYACA", value: "15646" },
    { label: "SAMANÁ - CALDAS", value: "17662" },
    { label: "SAMANIEGO - NARIÑO", value: "52678" },
    { label: "SAMPUÉS - SUCRE", value: "70670" },
    { label: "SAN AGUSTÍN - HUILA", value: "41668" },
    { label: "SAN ALBERTO - CESAR", value: "20710" },
    { label: "SAN ANDRES - ANTIOQUIA", value: "05647" },
    { label: "SAN ANDRÉS DE SOTAVENTO - CORDOBA", value: "23670" },
    { label: "SAN ANDRÉS ISLAS - SAN ANDRES, PROVIDENCIA Y STA CATALINA", value: "88001" },
    { label: "SAN ANDRÉS -SANTANDER - SANTANDER", value: "68669" },
    { label: "SAN ANTERO - CORDOBA", value: "23672" },
    { label: "SAN ANTONIO - TOLIMA", value: "73675" },
    { label: "SAN ANTONIO DE TEQUENDAMA - CUNDINAMARCA", value: "25645" },
    { label: "SAN BENITO - SANTANDER", value: "68673" },
    { label: "SAN BENITO ABAD - SUCRE", value: "70678" },
    { label: "SAN BERNARDO -CUNDI - CUNDINAMARCA", value: "25649" },
    { label: "SAN BERNARDO DEL VIENTO - CORDOBA", value: "23675" },
    { label: "SAN BERNARDO -NARINO - NARIÑO", value: "52685" },
    { label: "SAN CALIXTO - NORTE DE SANTANDER", value: "54670" },
    { label: "SAN CARLOS -ANTIOQUIA - ANTIOQUIA", value: "05649" },
    { label: "SAN CARLOS -CORDOBA - CORDOBA", value: "23678" },
    { label: "SAN CARLOS DE GUAROA - META", value: "50680" },
    { label: "SAN CAYETANO -CUNDIN - CUNDINAMARCA", value: "25653" },
    { label: "SAN CAYETANO NTE DE SANTA - NORTE DE SANTANDER", value: "54673" },
    { label: "SAN CRISTOBAL - BOLIVAR", value: "13620" },
    { label: "SAN DIEGO - CESAR", value: "20750" },
    { label: "SAN EDUARDO - BOYACA", value: "15660" },
    { label: "SAN ESTANISLAO - BOLIVAR", value: "13647" },
    { label: "SAN FELIPE - GUAINÍA", value: "94883" },
    { label: "SAN FERNANDO - BOLIVAR", value: "13650" },
    { label: "SAN FRANCISCO - PUTUMAYO", value: "86755" },
    { label: "SAN FRANCISCO -ANTIOQUIA - ANTIOQUIA", value: "05652" },
    { label: "SAN FRANCISCO -CUNDINAMAR - CUNDINAMARCA", value: "25658" },
    { label: "SAN GIL - SANTANDER", value: "68679" },
    { label: "SAN JACINTO - BOLIVAR", value: "13654" },
    { label: "SAN JACINTO DEL CAUCA - BOLIVAR", value: "13655" },
    { label: "SAN JERONIMO - ANTIOQUIA", value: "05656" },
    { label: "SAN JOAQUÍN - SANTANDER", value: "68682" },
    { label: "SAN JOSÉ - CALDAS", value: "17665" },
    { label: "SAN JOSÉ DE LA FRAGUA - CAQUETA", value: "18610" },
    { label: "SAN JOSE DE LA MONTAÑA - ANTIOQUIA", value: "05658" },
    { label: "SAN JOSÉ DE MIRANDA - SANTANDER", value: "68684" },
    { label: "SAN JOSÉ DE PARE - BOYACA", value: "15664" },
    { label: "SAN JOSÉ DEL GUAVIARE - GUAVIARE", value: "95001" },
    { label: "SAN JOSÉ DEL PALMAR - CHOCO", value: "27660" },
    { label: "SAN JUAN BETULIA - SUCRE", value: "70702" },
    { label: "SAN JUAN DE ARAMA - META", value: "50683" },
    { label: "SAN JUAN DE RIOSECO - CUNDINAMARCA", value: "25662" },
    { label: "SAN JUAN DE URABA - ANTIOQUIA", value: "05659" },
    { label: "SAN JUAN DEL CESAR - LA GUAJIRA", value: "44650" },
    { label: "SAN JUAN NEPOMUCENO - BOLIVAR", value: "13657" },
    { label: "SAN JUANITO - META", value: "50686" },
    { label: "SAN LORENZO - NARIÑO", value: "52687" },
    { label: "SAN LUIS -ANTIOQUIA - ANTIOQUIA", value: "05660" },
    { label: "SAN LUIS DE GACENO - BOYACA", value: "15667" },
    { label: "SAN LUIS DE PALENQUE - CASANARE", value: "85325" },
    { label: "SAN LUIS -TOLIMA - TOLIMA", value: "73678" },
    { label: "SAN MARCOS - SUCRE", value: "70708" },
    { label: "SAN MARTIN -CESAR - CESAR", value: "20770" },
    { label: "SAN MARTÍN DE LOBA - BOLIVAR", value: "13667" },
    { label: "SAN MARTIN -META - META", value: "50689" },
    { label: "SAN MATEO - BOYACA", value: "15673" },
    { label: "SAN MIGUEL DE SEMA - BOYACA", value: "15676" },
    { label: "SAN MIGUEL -SANTANDER - SANTANDER", value: "68686" },
    { label: "SAN MIGUEL-PUTUMAYO - PUTUMAYO", value: "86757" },
    { label: "SAN ONOFRE - SUCRE", value: "70713" },
    { label: "SAN PABLO -BOLIVAR - BOLIVAR", value: "13670" },
    { label: "SAN PABLO BORBUR - BOYACA", value: "15681" },
    { label: "SAN PABLO -NARINO - NARIÑO", value: "52693" },
    { label: "SAN PEDRO -ANTIOQUIA - ANTIOQUIA", value: "05664" },
    { label: "SAN PEDRO DE CARTAGO - NARIÑO", value: "52694" },
    { label: "SAN PEDRO DE URABA - ANTIOQUIA", value: "05665" },
    { label: "SAN PEDRO -SUCRE - SUCRE", value: "70717" },
    { label: "SAN PEDRO -VALLE DEL CAU - VALLE DEL CAUCA", value: "76670" },
    { label: "SAN PELAYO - CORDOBA", value: "23686" },
    { label: "SAN RAFAEL - ANTIOQUIA", value: "05667" },
    { label: "SAN ROQUE - ANTIOQUIA", value: "05670" },
    { label: "SAN SEBASTÍAN - CAUCA", value: "19693" },
    { label: "SAN SEBASTIÁN DE BUENAVISTA - MAGDALENA", value: "47692" },
    { label: "SAN VICENTE - ANTIOQUIA", value: "05674" },
    { label: "SAN VICENTE DE CHUCURÍ - SANTANDER", value: "68689" },
    { label: "SAN VICENTE DEL CAGUÁN - CAQUETA", value: "18753" },
    { label: "SAN ZENÓN - MAGDALENA", value: "47703" },
    { label: "SANDONÁ - NARIÑO", value: "52683" },
    { label: "SANTA ANA - MAGDALENA", value: "47707" },
    { label: "SANTA BÁRBARA -ANTIOQUIA - ANTIOQUIA", value: "05679" },
    { label: "SANTA BARBARA DE PINTO - MAGDALENA", value: "47720" },
    { label: "SANTA BÁRBARA -NARIÑO - NARIÑO", value: "52696" },
    { label: "SANTA BÁRBARA -SANTANDER - SANTANDER", value: "68705" },
    { label: "SANTA CATALINA - BOLIVAR", value: "13673" },
    { label: "SANTA CRUZ - NARIÑO", value: "52699" },
    { label: "SANTA HELENA DEL OPÓN - SANTANDER", value: "68720" },
    { label: "SANTA ISABEL - TOLIMA", value: "73686" },
    { label: "SANTA LUCIA - ATLANTICO", value: "08675" },
    { label: "SANTA MARÍA -BOYACA - BOYACA", value: "15690" },
    { label: "SANTA MARÍA -HUILA - HUILA", value: "41676" },
    { label: "SANTA MARTA - MAGDALENA", value: "47001" },
    { label: "SANTA RITA - VICHADA", value: "99572" },
    { label: "SANTA ROSA -BOLIVAR - BOLIVAR", value: "13683" },
    { label: "SANTA ROSA -CAUCA - CAUCA", value: "19701" },
    { label: "SANTA ROSA DE CABAL - RISARALDA", value: "66682" },
    { label: "SANTA ROSA DE OSOS - ANTIOQUIA", value: "05686" },
    { label: "SANTA ROSA DE VITERBO - BOYACA", value: "15693" },
    { label: "SANTA ROSA DEL SUR - BOLIVAR", value: "13688" },
    { label: "SANTA ROSALIA - VICHADA", value: "99624" },
    { label: "SANTA ROSALIA - VICHADA", value: "99666" },
    { label: "SANTA SOFÍA - BOYACA", value: "15696" },
    { label: "SANTAFE DE ANTIOQUIA - ANTIOQUIA", value: "05042" },
    { label: "SANTANA - BOYACA", value: "15686" },
    { label: "SANTANDER DE QUILICHAO - CAUCA", value: "19698" },
    { label: "SANTIAGO - NORTE DE SANTANDER", value: "54680" },
    { label: "SANTIAGO - PUTUMAYO", value: "86760" },
    { label: "SANTIAGO DE TOLÚ - SUCRE", value: "70820" },
    { label: "SANTO DOMINGO - ANTIOQUIA", value: "05690" },
    { label: "SANTO TOMAS - ATLANTICO", value: "08685" },
    { label: "SANTUARIO - RISARALDA", value: "66687" },
    { label: "SAPUYES - NARIÑO", value: "52720" },
    { label: "SARAVENA - ARAUCA", value: "81736" },
    { label: "SARDINATA - NORTE DE SANTANDER", value: "54720" },
    { label: "SASAIMA - CUNDINAMARCA", value: "25718" },
    { label: "SATIVANORTE - BOYACA", value: "15720" },
    { label: "SATIVASUR - BOYACA", value: "15723" },
    { label: "SEGOVIA - ANTIOQUIA", value: "05736" },
    { label: "SESQUILÉ - CUNDINAMARCA", value: "25736" },
    { label: "SEVILLA - VALLE DEL CAUCA", value: "76736" },
    { label: "SIACHOQUE - BOYACA", value: "15740" },
    { label: "SIBATÉ - CUNDINAMARCA", value: "25740" },
    { label: "SIBUNDOY - PUTUMAYO", value: "86749" },
    { label: "SILOS - NORTE DE SANTANDER", value: "54743" },
    { label: "SILVANIA - CUNDINAMARCA", value: "25743" },
    { label: "SILVIA - CAUCA", value: "19743" },
    { label: "SIMACOTA - SANTANDER", value: "68745" },
    { label: "SIMIJACA - CUNDINAMARCA", value: "25745" },
    { label: "SIMITÍ - BOLIVAR", value: "13744" },
    { label: "SINCÉ - SUCRE", value: "70742" },
    { label: "SINCELEJO - SUCRE", value: "70001" },
    { label: "SIPÍ - CHOCO", value: "27745" },
    { label: "SITIONUEVO - MAGDALENA", value: "47745" },
    { label: "SOACHA - CUNDINAMARCA", value: "25754" },
    { label: "SOATÁ - BOYACA", value: "15753" },
    { label: "SOCHA - BOYACA", value: "15757" },
    { label: "SOCORRO - SANTANDER", value: "68755" },
    { label: "SOCOTÁ - BOYACA", value: "15755" },
    { label: "SOGAMOSO - BOYACA", value: "15759" },
    { label: "SOLANO - CAQUETA", value: "18756" },
    { label: "SOLEDAD - ATLANTICO", value: "08758" },
    { label: "SOLITA - CAQUETA", value: "18785" },
    { label: "SOMONDOCO - BOYACA", value: "15761" },
    { label: "SONSON - ANTIOQUIA", value: "05756" },
    { label: "SOPETRAN - ANTIOQUIA", value: "05761" },
    { label: "SOPLAVIENTO - BOLIVAR", value: "13760" },
    { label: "SOPÓ - CUNDINAMARCA", value: "25758" },
    { label: "SORA - BOYACA", value: "15762" },
    { label: "SORACÁ - BOYACA", value: "15764" },
    { label: "SOTAQUIRÁ - BOYACA", value: "15763" },
    { label: "SOTARÁ - CAUCA", value: "19760" },
    { label: "SUAITA - SANTANDER", value: "68770" },
    { label: "SUAN - ATLANTICO", value: "08770" },
    { label: "SUÁREZ -CAUCA - CAUCA", value: "19780" },
    { label: "SUÁREZ -TOLIMA - TOLIMA", value: "73770" },
    { label: "SUAZA - HUILA", value: "41770" },
    { label: "SUBA - BOGOTA D.C", value: "11769" },
    { label: "SUBACHOQUE - CUNDINAMARCA", value: "25769" },
    { label: "SUCRE -SANTANDER - SANTANDER", value: "68773" },
    { label: "SUCRE -SUCRE - SUCRE", value: "70771" },
    { label: "SUCRE-CAUCA - CAUCA", value: "19785" },
    { label: "SUESCA - CUNDINAMARCA", value: "25772" },
    { label: "SUPATÁ - CUNDINAMARCA", value: "25777" },
    { label: "SUPÍA - CALDAS", value: "17777" },
    { label: "SURATÁ - SANTANDER", value: "68780" },
    { label: "SUSA - CUNDINAMARCA", value: "25779" },
    { label: "SUSACÓN - BOYACA", value: "15774" },
    { label: "SUTAMARCHÁN - BOYACA", value: "15776" },
    { label: "SUTATAUSA - CUNDINAMARCA", value: "25781" },
    { label: "SUTATENZA - BOYACA", value: "15778" },
    { label: "TABIO - CUNDINAMARCA", value: "25785" },
    { label: "TADÓ - CHOCO", value: "27787" },
    { label: "TALAIGUA NUEVO - BOLIVAR", value: "13780" },
    { label: "TAMALAMEQUE - CESAR", value: "20787" },
    { label: "TÁMARA - CASANARE", value: "85400" },
    { label: "TAME - ARAUCA", value: "81794" },
    { label: "TAMESIS - ANTIOQUIA", value: "05789" },
    { label: "TAMINANGO - NARIÑO", value: "52786" },
    { label: "TANGUA - NARIÑO", value: "52788" },
    { label: "TARAIRA - VAUPÉS", value: "97666" },
    { label: "TARAPACÁ - AMAZONAS", value: "91798" },
    { label: "TARAZA - ANTIOQUIA", value: "05790" },
    { label: "TARQUI - HUILA", value: "41791" },
    { label: "TARSO - ANTIOQUIA", value: "05792" },
    { label: "TASCO - BOYACA", value: "15790" },
    { label: "TAURAMENA - CASANARE", value: "85410" },
    { label: "TAUSA - CUNDINAMARCA", value: "25793" },
    { label: "TELLO - HUILA", value: "41799" },
    { label: "TENA - CUNDINAMARCA", value: "25797" },
    { label: "TENERIFE - MAGDALENA", value: "47798" },
    { label: "TENJO - CUNDINAMARCA", value: "25799" },
    { label: "TENZA - BOYACA", value: "15798" },
    { label: "TEORAMA - SANTANDER", value: "68542" },
    { label: "TEQUENDAMA - NORTE DE SANTANDER", value: "54800" },
    { label: "TERUEL - HUILA", value: "41801" },
    { label: "TESALIA - HUILA", value: "41797" },
    { label: "TIBACUY - CUNDINAMARCA", value: "25805" },
    { label: "TIBANÁ - BOYACA", value: "15804" },
    { label: "TIBASOSA - BOYACA", value: "15806" },
    { label: "TIBIRITA - CUNDINAMARCA", value: "25807" },
    { label: "TIBÚ - NORTE DE SANTANDER", value: "54810" },
    { label: "TIERRALTA - CORDOBA", value: "23807" },
    { label: "TIMANÁ - HUILA", value: "41807" },
    { label: "TIMBÍO - CAUCA", value: "19807" },
    { label: "TIMBIQUÍ - CAUCA", value: "19809" },
    { label: "TINJACÁ - BOYACA", value: "15808" },
    { label: "TIPACOQUE - BOYACA", value: "15810" },
    { label: "TIQUISIO - BOLIVAR", value: "13810" },
    { label: "TITIRIBI - ANTIOQUIA", value: "05809" },
    { label: "TOCA - BOYACA", value: "15814" },
    { label: "TOCAIMA - CUNDINAMARCA", value: "25815" },
    { label: "TOCANCIPÁ - CUNDINAMARCA", value: "25817" },
    { label: "TOGÜÍ - BOYACA", value: "15816" },
    { label: "TOLEDO -ANTIOQUIA - ANTIOQUIA", value: "05819" },
    { label: "TOLEDO -NTE DE SANTAN - NORTE DE SANTANDER", value: "54820" },
    { label: "TOLUVIEJO - SUCRE", value: "70823" },
    { label: "TONA - SANTANDER", value: "68820" },
    { label: "TOPAGA - BOYACA", value: "15820" },
    { label: "TOPAIPÍ - CUNDINAMARCA", value: "25823" },
    { label: "TORIBÍO - CAUCA", value: "19821" },
    { label: "TORO - VALLE DEL CAUCA", value: "76823" },
    { label: "TOTA - BOYACA", value: "15822" },
    { label: "TOTORÓ - CAUCA", value: "19824" },
    { label: "TRINIDAD - CASANARE", value: "85430" },
    { label: "TRUJILLO - VALLE DEL CAUCA", value: "76828" },
    { label: "TUBARÁ - ATLANTICO", value: "08832" },
    { label: "TULUÁ - VALLE DEL CAUCA", value: "76834" },
    { label: "TUMACO - NARIÑO", value: "52835" },
    { label: "TUNJA - BOYACA", value: "15001" },
    { label: "TUNUNGUÁ - BOYACA", value: "15832" },
    { label: "TÚQUERRES - NARIÑO", value: "52838" },
    { label: "TURBACO - BOLIVAR", value: "13836" },
    { label: "TURBANÁ - BOLIVAR", value: "13838" },
    { label: "TURBO - ANTIOQUIA", value: "05837" },
    { label: "TURMEQUÉ - BOYACA", value: "15835" },
    { label: "TUTA - BOYACA", value: "15837" },
    { label: "TUTASÁ - BOYACA", value: "15839" },
    { label: "UBALÁ - CUNDINAMARCA", value: "25839" },
    { label: "UBAQUE - CUNDINAMARCA", value: "25841" },
    { label: "UBATÉ - CUNDINAMARCA", value: "25843" },
    { label: "ULLOA - VALLE DEL CAUCA", value: "76845" },
    { label: "UMBITA - BOYACA", value: "15842" },
    { label: "UNE - CUNDINAMARCA", value: "25845" },
    { label: "UNGUÍA - CHOCO", value: "27800" },
    { label: "UNIÓN PANAMERICANA - CHOCO", value: "27810" },
    { label: "URAMITA - ANTIOQUIA", value: "05842" },
    { label: "URIBE - META", value: "50370" },
    { label: "URIBIA - LA GUAJIRA", value: "44847" },
    { label: "URRAO - ANTIOQUIA", value: "05847" },
    { label: "URUMITA - LA GUAJIRA", value: "44855" },
    { label: "USAQUEN - BOGOTA D.C", value: "11848" },
    { label: "USIACURÍ - ATLANTICO", value: "08849" },
    { label: "USME - BOGOTA D.C", value: "11850" },
    { label: "ÚTICA - CUNDINAMARCA", value: "25851" },
    { label: "VALDIVIA - ANTIOQUIA", value: "05854" },
    { label: "VALENCIA - CORDOBA", value: "23855" },
    { label: "VALLE DE SAN JOSÉ - SANTANDER", value: "68855" },
    { label: "VALLE DE SAN JUAN - TOLIMA", value: "73854" },
    { label: "VALLE DEL GUAMUEZ - PUTUMAYO", value: "86865" },
    { label: "VALLEDUPAR - CESAR", value: "20001" },
    { label: "VALPARAISO -ANTIOQUIA - ANTIOQUIA", value: "05856" },
    { label: "VALPARAISO -CAQUETA - CAQUETA", value: "18860" },
    { label: "VEGACHI - ANTIOQUIA", value: "05858" },
    { label: "VÉLEZ - SANTANDER", value: "68861" },
    { label: "VENADILLO - TOLIMA", value: "73861" },
    { label: "VENECIA -ANTIOQUIA - ANTIOQUIA", value: "05861" },
    { label: "VENECIA -CUNDINAMARCA - CUNDINAMARCA", value: "25506" },
    { label: "VENTAQUEMADA - BOYACA", value: "15861" },
    { label: "VERGARA - CUNDINAMARCA", value: "25862" },
    { label: "VERSALLES - VALLE DEL CAUCA", value: "76863" },
    { label: "VETAS - SANTANDER", value: "68867" },
    { label: "VIANÍ - CUNDINAMARCA", value: "25867" },
    { label: "VICTORIA - CALDAS", value: "17867" },
    { label: "VIGIA DEL FUERTE - ANTIOQUIA", value: "05873" },
    { label: "VIJES - VALLE DEL CAUCA", value: "76869" },
    { label: "VILLA CARO - NORTE DE SANTANDER", value: "54871" },
    { label: "VILLA DE LEYVA - BOYACA", value: "15407" },
    { label: "VILLA DEL ROSARIO - NORTE DE SANTANDER", value: "54874" },
    { label: "VILLA RICA - CAUCA", value: "19845" },
    { label: "VILLAGARZÓN - PUTUMAYO", value: "86885" },
    { label: "VILLAGÓMEZ - CUNDINAMARCA", value: "25871" },
    { label: "VILLAHERMOSA - TOLIMA", value: "73870" },
    { label: "VILLAMARÍA - CALDAS", value: "17873" },
    { label: "VILLANUEVA -BOLIVAR - BOLIVAR", value: "13873" },
    { label: "VILLANUEVA -CASANARE - CASANARE", value: "85440" },
    { label: "VILLANUEVA -GUAJIRA - LA GUAJIRA", value: "44874" },
    { label: "VILLANUEVA -SANTANDER - SANTANDER", value: "68872" },
    { label: "VILLAPINZÓN - CUNDINAMARCA", value: "25873" },
    { label: "VILLARRICA - TOLIMA", value: "73873" },
    { label: "VILLAVICENCIO - META", value: "50001" },
    { label: "VILLAVIEJA - HUILA", value: "41872" },
    { label: "VILLETA - CUNDINAMARCA", value: "25875" },
    { label: "VIOTÁ - CUNDINAMARCA", value: "25878" },
    { label: "VIRACACHÁ - BOYACA", value: "15879" },
    { label: "VISTA HERMOSA - META", value: "50711" },
    { label: "VITERBO - CALDAS", value: "17877" },
    { label: "YACOPÍ - CUNDINAMARCA", value: "25885" },
    { label: "YACUANQUER - NARIÑO", value: "52885" },
    { label: "YAGUARÁ - HUILA", value: "41885" },
    { label: "YALI - ANTIOQUIA", value: "05885" },
    { label: "YARUMAL - ANTIOQUIA", value: "05887" },
    { label: "YAVARATE - VAUPÉS", value: "97889" },
    { label: "YOLOMBO - ANTIOQUIA", value: "05890" },
    { label: "YONDO - ANTIOQUIA", value: "05893" },
    { label: "YOPAL - CASANARE", value: "85001" },
    { label: "YOTOCO - VALLE DEL CAUCA", value: "76890" },
    { label: "YUMBO - VALLE DEL CAUCA", value: "76892" },
    { label: "ZAMBRANO - BOLIVAR", value: "13894" },
    { label: "ZAPATOCA - SANTANDER", value: "68895" },
    { label: "ZAPAYÁN - MAGDALENA", value: "47960" },
    { label: "ZARAGOZA - ANTIOQUIA", value: "05895" },
    { label: "ZARZAL - VALLE DEL CAUCA", value: "76895" },
    { label: "ZETAQUIRA - BOYACA", value: "15897" },
    { label: "ZIPACÓN - CUNDINAMARCA", value: "25898" },
    { label: "ZIPAQUIRÁ - CUNDINAMARCA", value: "25899" },
    { label: "ZONA BANANERA - MAGDALENA", value: "47980" },
  ];    